version: '3.9'
services:
  # In Docker
  # - DATABASE_URL=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - DATABASE_URL=postgres://prisma:prisma@localhost:5432/

  db:
    image: postgres:13
    restart: always
    container_name: postgres-with-prisma
    ports:
      - "${HOST_PORT}:5432" # HOST_PORT:CONTAINER_PORT
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma